apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "auth0"
  namespace: demo
spec:
  jwtRules:
  - issuer: "https://dev-2wq-dyxn.us.auth0.com/"
    jwksUri: "https://dev-2wq-dyxn.us.auth0.com/.well-known/jwks.json"
